version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: andres
      POSTGRES_DB: my_store
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  mysql_db:
    image: mysql:5
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_store
      MYSQL_PORT: 33060
    ports:
      - 33060:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80